config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update] do
    member do
      get :following, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end
  resources :books do
    resource :favorites,only: [:create,:destroy]
    resources :book_comments,only: [:create,:destroy]
  end
  get 'search' => 'search#search'
  get 'date_search' => 'search#date_search'
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :book
  belongs_to :user

  validates :comment, presence: true

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    book_comment = BookComment.new(book_comment_params)
    book_comment.user_id = current_user.id
    book_comment.book_id = @book.id
    book_comment.save
    # redirect_to book_path(book)
  end

  def destroy
    book_comment = BookComment.find_by(id: params[:id], book_id: params[:book_id])
    book_comment.destroy
    redirect_to request.referer
  end

  private

    def book_comment_params
      params.require(:book_comment).permit(:comment)
    end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comment.html.erb
  <h2>Book comments</h2>
    <table class="table">
      <% book.book_comments.each do |book_comment| %>
      <tr>
        <td>
          <%= link_to user_path(book_comment.user) do %>
            <%= attachment_image_tag(book_comment.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= book_comment.user.name %>
          <% end %>
        </td>
        <td><%= book_comment.comment %></td>
        <% if book_comment.user == current_user %>
        <td>
          <%= link_to book_book_comment_path(book_comment.book_id, book_comment), method: :delete, "data-confirm" => "Are you sure to delete your comment?", class:"btn btn-danger btn-sm" do %>Destroy<% end %>
        </td>
        <% end %>
      </tr>
      <% end %>
    </table>

app/views/book_comments/create.js.erb
$("#book_<%= @book.id %> .comments_count").html("コメント数: <%= @book.book_comments.count %>");
$(".comment_index").html("<%= j(render 'book_comments/comment', book: @book) %>");
$("#text_area").val(" ");

<!--$('.text_area')[0].reset();-->