config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update] do
    member do
      get :following, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end
  resources :books do
    resource :favorites,only: [:create,:destroy]
    resources :book_comments,only: [:create,:destroy]
  end
  get 'search' => 'search#search'
  get 'date_search' => 'search#date_search'
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(other_user)

    unless self == other_user
      self.active_relationships.find_or_create_by(followed_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.active_relationships.find_by(followed_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(user)
    following.include?(user)
  end

  attachment :profile_image, destroy: false

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}


  def self.looks(searches, words)
		if searches == 'perfect_match'
			@users = User.where("name LIKE?","#{words}")
		elsif searches == 'forward_match'
			@users = User.where("name LIKE?","#{words}%")
		elsif searches == 'back_match'
			@users = User.where("name LIKE?","%#{words}")
		elsif searches == 'partial_match'
			@users = User.where("name LIKE?","%#{words}%")
		else
			@users = User.all
		end
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @today_book = @books.where(created_at: Date.today.all_day).count
    @yesterday_book = @books.where(created_at: 1.day.ago.all_day).count
    @this_week_book = @books.where(created_at: Date.today.all_week).count
    @last_week_book = @books.where(created_at: 1.week.ago.all_week).count
      # 以下解答例
      # @today_book =  @books.created_today
    @two_days_ago_book = @books.where(created_at: 2.days.ago.all_day).count
    @three_days_ago_book = @books.where(created_at: 3.days.ago.all_day).count
    @four_days_ago_book = @books.where(created_at: 4.days.ago.all_day).count
    @five_days_ago_book = @books.where(created_at: 5.days.ago.all_day).count
    @six_days_ago_book = @books.where(created_at: 6.days.ago.all_day).count
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def following
    @users = User.find(params[:id]).following.where.not(id: current_user.id)
  end

  def followers
    @users = User.find(params[:id]).followers.where.not(id: current_user.id)
  end
  

  
  

  private
    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end
  
    def ensure_correct_user
      @user = User.find(params[:id])
      unless @user == current_user
        redirect_to user_path(current_user)
      end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.following.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <% unless user == current_user %>
          <% if current_user.following?(user) %>
            <td>
              <%= link_to "フォロー外す", user_relationships_path(user), method: :delete, class: "btn btn-info btn-sm" %>
            </td>
          <% else %>
            <td>
              <%= link_to "フォローする", user_relationships_path(user), method: :post, class: "btn btn-outline-info btn-sm" %>
            </td>
          <% end %>
        <% else %>
        <td></td>
        <% end %>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.following.count, following_user_path(user) %></th>
  </tr>
  <tr>
    <th>follower</td>
    <th><%= link_to user.followers.count, followers_user_path(user) %></th>
  </tr>
</table>

<div class='row'>
  <% unless user == current_user %>
    <% if current_user.following?(user) %>
      <%= link_to "フォロー外す", user_relationships_path(user), method: :delete, class: 'btn btn-info btn-block' %>
    <% else %>
      <%= link_to 'フォローする', user_relationships_path(user), method: :post, class: 'btn btn-outline-info btn-block' %>
    <% end %>
  <% end %>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>

app/views/users/_record.html.erb
<table class="table">
  <thead>
    <tr>
      <th>今日の投稿数</th>
      <th>前日の投稿数</th>
      <th>前日比</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @today_book %></td>
      <td><%= @yesterday_book %></td>
      <% if @yesterday_book == 0 %>
      <td>Error</td>
      <% else %>
      <td><%= (@today_book.quo(@yesterday_book) * 100).round %>%</td>
      <% end %>
    </tr>
  </tbody>

    <thead>
    <tr>
      <th>今週の投稿数</th>
      <th>前週の投稿数</th>
      <th>前週比</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @this_week_book %></td>
      <td><%= @last_week_book %></td>
      <% if @last_week_book == 0 %>
      <td>Error</td>
      <% else %>
      <td><%= (@this_week_book.quo(@last_week_book) * 100).round %>%</td>
      <% end %>
    </tr>
  </tbody>
</table>

app/views/users/_week-record.html.erb
<table class="table">
  <thead>
    <tr>
      <th>6日前</th>
      <th>5日前</th>
      <th>4日前</th>
      <th>3日前</th>
      <th>2日前</th>
      <th>1日前</th>
      <th>今日</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @six_days_ago_book %></td>
      <td><%= @five_days_ago_book %></td>
      <td><%= @four_days_ago_book %></td>
      <td><%= @three_days_ago_book %></td>
      <td><%= @two_days_ago_book %></td>
      <td><%= @yesterday_book %></td>
      <td><%= @today_book %></td>
    </tr>
  </tbody>
</table>

<canvas id="myLineChart">
</canvas>

<script>
  $(document).on('turbolinks:load', function(){
    var ctx = document.getElementById("myLineChart");
    var myLineChart = new Chart(ctx, {
      type: 'line',
      data: {
       //データ項目のラベル
        labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '前日', '今日'],
        datasets: [
          {
           //凡例のラベル
            label: '投稿した本の数',
            data: [
              <%= @six_days_ago_book %>,
              <%= @five_days_ago_book %>,
              <%= @four_days_ago_book %>,
              <%= @three_days_ago_book %>,
              <%= @two_days_ago_book %>,
              <%= @yesterday_book %>,
              <%= @today_book %>
              ], //グラフのデータ
            borderColor: "rgba(200,112,126,1)",
            backgroundColor: "rgba(0,0,0,0)"
          }
        ],
      },
      options: {
        title: {
          display: true,
          //グラフタイトル
          text: '7日間の投稿数の比較'
        },
        scales: {
          yAxes: [{
            ticks: {
              suggestedMax: 10,  //最大値
              suggestedMin: 0,  //最小値
              stepSize: 1, //縦ラベルの数値単位
            }
          }]
        },
      }
    });
  });
</script>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h2>Follower Users</h2>
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.following.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/following.html.erb
<h2>Follow Users</h2>
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.following.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index', books: @books %>
      
      <%= form_tag(date_search_path, :method => 'get', remote:true) do %>
        <%= date_field_tag :date_search %>
        <%= submit_tag 'Search', class:"btn btn-outline-dark" %>
      <% end %>
      <div class="date-search-result"></div>
      
      <h3 class="mt-3">投稿数の前日比・前週比</h3>
      <%= render 'record' %>
      
      <h3 class="mt-3">7日間分の投稿数</h3>
      <%= render 'week-record' %>
    </div>
  </div>
</div>